name: APK Compilation (Android)

on:
  workflow_dispatch:

env:
  JAVA_VERSION: "17.x"
  FLUTTER_VERSION: 3.24.5

jobs:
  apk_compilation: 
    name: "APK Compilation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: "gradle" 

      # Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION  }}
          cache: true

      # Install Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Generate Debug Keystore (Required for Signing)
      - name: Generate Debug Keystore
        run: |
          mkdir -p ~/.android
          keytool -genkeypair -v -keystore ~/.android/debug.keystore -storetype PKCS12 -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US" -storepass android -keypass android -alias androiddebugkey

      # Build Release APK (Signed with Debug Keystore)
      - run: flutter build apk --release --split-per-abi

      # Upload APK (Only arm64-v8a)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
